const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info:{
        version: "0.1.0",
        title:"Movie Rest API with Swagger",
        description:"Documentation generated by the <b><i>swagger-autogen</i></b> module"
    },
    host:"localhost:3000",
    basePath:"/",
    schemes:["http", "https"],
    consumes:["application.json"],
    produces:["application.json"],
    tags:[
        {
            "name":"Movie",
            "description":"Movies information"
        },
        {
            "name":"Rent",
            "description":"Information of rented movies"
        }
    ],

    definitions:{
        Movie:{
            "id": 10002,
            "name": "lord of the rings",
            "year": "1999",
            "genre": "adventure",
            "income": 5498700
        },
        Movies:[
            {
                "id": 10002,
                "name": "lord of the rings",
                "year": "1999",
                "genre": "adventure",
                "income": 5498700
             },
            {
                "id": 10003,
                "name": "ghost",
                "year": "1982",
                "genre": "thrill",
                "income": 235168
            },
            {
                "id": 10004,
                "name": "die hard",
                "year": "1999",
                "genre": "action",
                "income": 10000000
            }
        ],
        Rent:{
            "movieId": 10002,
            "duration": 10,
            "person": "Hi Coders"
        },
        Rents:[
            {
                "movieId": 10002,
                "duration": 10,
                "person": "Hi Coders"
            },
            {
                "movieId": 10003,
                "duration": 3,
                "person": "Murat"
            },
            {
                "movieId": 10001,
                "duration": 11,
                "person": "Mehmet"
            }
        ]
    }
}



const outputFile = './swagger.json';
const endpointsFile = ['./app.js'];

swaggerAutogen(outputFile, endpointsFile, doc).then(()=>{
    require('./app');
})